// <auto-generated />
using KidsTime.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KidsTime.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200414095457_Phone")]
    partial class Phone
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KidsTime.Models.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivityStar")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            ActivityId = 1,
                            CategoryId = 3,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2019/05/24/16/49/brushes-4226688_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2019/05/24/16/49/brushes-4226688_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Pictura",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Viata in culori"
                        },
                        new
                        {
                            ActivityId = 2,
                            CategoryId = 3,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2016/08/24/20/39/violin-1617972_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2016/08/24/20/39/violin-1617972_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Vioara",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Viata intre vibratii"
                        },
                        new
                        {
                            ActivityId = 3,
                            CategoryId = 3,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2018/05/12/15/13/amateur-3393588_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2018/05/12/15/13/amateur-3393588_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Dansuri populare",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Ne conectam cu bunnii si strabunii"
                        },
                        new
                        {
                            ActivityId = 4,
                            CategoryId = 3,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2017/09/03/16/16/musical-2710927_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2017/09/03/16/16/musical-2710927_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Teatru",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Teatru de revista"
                        },
                        new
                        {
                            ActivityId = 5,
                            CategoryId = 3,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2015/02/03/16/14/potter-622708_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2015/02/03/16/14/potter-622708_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Ceramica",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Dam viata lutului"
                        },
                        new
                        {
                            ActivityId = 6,
                            CategoryId = 4,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2015/09/21/15/10/geisha-949978_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2015/09/21/15/10/geisha-949978_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Japonia",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Cultura si civilizatia Japoniei"
                        },
                        new
                        {
                            ActivityId = 7,
                            CategoryId = 4,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2016/08/15/08/22/greece-1594689_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2016/08/15/08/22/greece-1594689_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Grecia",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Cultura si civilizatia Greciei"
                        },
                        new
                        {
                            ActivityId = 8,
                            CategoryId = 1,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2020/04/07/09/07/go-kart-5012595_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2020/04/07/09/07/go-kart-5012595_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Karting",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Simte viteza"
                        },
                        new
                        {
                            ActivityId = 9,
                            CategoryId = 1,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2013/05/20/05/19/rollerderby-112223_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2013/05/20/05/19/rollerderby-112223_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Patinaj viteza",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Sa invartim rotile"
                        },
                        new
                        {
                            ActivityId = 10,
                            CategoryId = 2,
                            ImageThumbnailURl = "https://cdn.pixabay.com/photo/2016/06/13/08/00/pi-1453839_1280.jpg",
                            ImageURl = "https://cdn.pixabay.com/photo/2016/06/13/08/00/pi-1453839_1280.jpg",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Matematica aplicata",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Sa invartim rotile"
                        },
                        new
                        {
                            ActivityId = 11,
                            CategoryId = 1,
                            ImageThumbnailURl = "https://scontent.fotp3-3.fna.fbcdn.net/v/t1.0-9/10676376_749670175148758_8086599348838060691_n.jpg?_nc_cat=108&_nc_sid=85a577&_nc_ohc=DxyQnDW55NcAX_D8i_S&_nc_ht=scontent.fotp3-3.fna&oh=3cb0b394586a2aa7cf77dc591efa775e&oe=5EB58729",
                            ImageURl = "https://scontent.fotp3-3.fna.fbcdn.net/v/t1.0-9/10676376_749670175148758_8086599348838060691_n.jpg?_nc_cat=108&_nc_sid=85a577&_nc_ohc=DxyQnDW55NcAX_D8i_S&_nc_ht=scontent.fotp3-3.fna&oh=3cb0b394586a2aa7cf77dc591efa775e&oe=5EB58729",
                            IsActivityStar = true,
                            IsAvailable = true,
                            LongDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
                            Name = "Aeromodele",
                            PhoneNumber = 0,
                            Price = 20m,
                            ShortDescription = "Sa coboram rotile"
                        });
                });

            modelBuilder.Entity("KidsTime.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Sport",
                            Description = "Sport"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Tehnica",
                            Description = "Tehnica"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Arta",
                            Description = "Arta"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Cultura",
                            Description = "Description"
                        });
                });

            modelBuilder.Entity("KidsTime.Models.Activity", b =>
                {
                    b.HasOne("KidsTime.Models.Category", "Category")
                        .WithMany("Activities")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
